import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Buomkuoth",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Haniyam",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: "1",
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      brand: "nike",
      image: "/images/photo-1562157873-818bc0726f68.avif",
      price: 120,
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: "High quality shirt",
    },
    {
      //_id: "2",
      name: "Nike Shirt",
      slug: "nike-shirt",
      category: "Shirts",
      image: "/images/photo-1434389677669-e08b4cac3105.avif",
      brand: "nike",
      price: 150,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "High quality shirt",
    },
    {
      //_id: "3",
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/photo-1585487000160-6ebcfceb0d03.avif",
      brand: "nike",
      price: 100,
      countInStock: 10,
      rating: 4.5,
      numReviews: 8,
      description: "High quality shirt",
    },
    {
      //_id: "4",
      name: "Shirt",
      slug: "shirt",
      category: "Shirts",
      image: "/images/photo-1552664199-fd31f7431a55.avif",
      brand: "nike",
      price: 75,
      countInStock: 10,
      rating: 3.5,
      numReviews: 7,
      description: "High quality shirt",
    },
  ],
};

export default data;
