const data = {
  products: [
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/photo-1562157873-818bc0726f68.avif",
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReview: 10,
      description: "High quality shirt",
    },
    {
      name: "Nike Shirt",
      slug: "nike-shirt",
      category: "Shirts",
      image: "/images/photo-1434389677669-e08b4cac3105.avif",
      price: 150,
      countInStock: 10,
      rating: 4.5,
      numReview: 10,
      description: "High quality shirt",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/photo-1585487000160-6ebcfceb0d03.avif",
      price: 100,
      countInStock: 10,
      rating: 4.5,
      numReview: 10,
      description: "High quality shirt",
    },
    {
      name: "Shirt",
      slug: "shirt",
      category: "Shirts",
      image: "/images/photo-1552664199-fd31f7431a55.avif",
      price: 75,
      countInStock: 10,
      rating: 4.5,
      numReview: 10,
      description: "High quality shirt",
    },
  ],
};

export default data;
